# Generated by Django 2.0.13 on 2020-01-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='state',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
