# Generated by Django 2.0.13 on 2019-12-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sulg',
            field=models.SlugField(blank=True),
        ),
    ]
