# Generated by Django 2.0.13 on 2019-12-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_product_sulg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sulg',
            new_name='slug',
        ),
    ]
