# Generated by Django 2.0.13 on 2020-02-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootstrap_form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='phone',
            new_name='address',
        ),
    ]
